version: "3.8"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./
      target: development
    volumes:
      - ./:/app
    command: yarn start
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      JWT_SECRET: hard_to_guess_secret_123
      PORT: 5001
    ports:
      - 5001:5001
      - 9229:9229

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432