version: "3.8"

networks:
  myness_nginx:
    external: true
    name: 'myness_nginx'
  myness_back:

services:
  postgres:
    image: postgres:13
    networks:
      myness_back:
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    networks:
      myness_back:
    ports:
      - 6379:6379

  api:
    container_name: api
    restart: unless-stopped
    networks:
      myness_nginx:
      myness_back:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      DB_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      JWT_SECRET: hard_to_guess_secret_123
      PORT: 5001
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "5001:5001"
    depends_on:
      - postgres
      - redis